# Generated by Django 3.0.6 on 2020-07-10 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overviewpage', '0002_auto_20200627_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_first', models.FileField(blank=True, null=True, upload_to='')),
                ('image_secondary', models.FileField(blank=True, null=True, upload_to='')),
                ('description_first', models.TextField()),
                ('description_second', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProjectCategory', models.CharField(choices=[('0', 'Apartment Website'), ('1', 'Cosmonaut Game'), ('2', 'This Website')], default='0', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
