# Generated by Django 3.0.6 on 2020-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overviewpage', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_first',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_second',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='title_highlight',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
    ]
